### ISSUE TITLE
GetIterator recursively converts the Map to an array 

### ISSUE THREAD

**Issue by deevus** [haldayne/boost#2]
The `GetIterator` method calls `toArray` internally which recursively converts the entire `Map` object to an `array`. 

`GetIterator` should not mutate the `Map` in any way, and should return the key value pairs as is. Using a generator would solve this. 

If PRs are welcome I'd be happy to look at it

**Comment by bishopb** [comment]
Yep, and IIRC, it does so because the Map might have non-scalar keys. To iterate a map:

```
foreach ($map->keys() as $key) {
    $value = $map[$key];
    // ...
}
```

This is annoying and reduces code clarity. For the common case of scalar keys, it'd be nice to not mutate in this way. PR welcomed!
